name: GitHub Pages

on:
  push:
    branches:
      - main
  schedule:
    - cron: 0 0 * * *

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
    
    name: Build Satis and Deploy to GH Pages

    steps:
    - uses: actions/checkout@v4

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v3
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

    - name: Install dependencies
      run: |
        composer -g config github-oauth.github.com ${{ secrets.GH_TOKEN }}
        composer install --prefer-dist --no-interaction --no-progress

    - name: Build Satis 
      run: composer satis:build ./satis.json ./public
      
    - name: Deploy
      uses: JamesIves/github-pages-deploy-action@v4
      with:
        BRANCH: gh-pages
        FOLDER: public
        CLEAN: true
